### PR TITLE
Add a 14.0.6 linked version

### PR DESCRIPTION
**Pull request by kurapov-peter**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kurapov-peter** [comment]
Hi, the idea of the PR was to provide a spirv translator version that's linked against llvm 14.0.6 (in a conda label for example?), not sure this is the way. Should I change the translator version accordingly? SHA stays the same.

**Comment by kurapov-peter** [comment]
@isuruf, could you please review?

**Comment by isuruf** [comment]
I don't think this is needed.

`llvm-spirv=14.0.0` is linked to `llvm 14.0.*` which means `llvm-spirv=14.0.0` works with `llvm=14.0.6` too.

For eg: `$ mamba create -n llvm-spirv llvm-spirv=14` gives me,

```
  + _libgcc_mutex      0.1  conda_forge  conda-forge/linux-64     Cached
  + _openmp_mutex      4.5  2_gnu        conda-forge/linux-64     Cached
  + libgcc-ng       12.2.0  h65d4601_19  conda-forge/linux-64      954kB
  + libgomp         12.2.0  h65d4601_19  conda-forge/linux-64      466kB
  + libllvm14       14.0.6  he0ac6c6_0   conda-forge/linux-64     Cached
  + libstdcxx-ng    12.2.0  h46fd767_19  conda-forge/linux-64        4MB
  + libzlib         1.2.13  h166bdaf_4   conda-forge/linux-64       66kB
  + llvm-spirv      14.0.0  he0ac6c6_1   conda-forge/linux-64        1MB
```

note that `libllvm14=14.0.6` is used.

**Comment by kurapov-peter** [comment]
Ok, let me check once again, but for me, llvm-spirv-14.0.0 does not work with llvm-14.0.6 properly. I'm not familiar with conda processes. Is it actually building llvm-spirv and linking it against llvm 14.0.6 in your example? If not, I wouldn't assume it should work.

**Pull request closed without merging**
