### PR TITLE
Update to 18.1.0

### PR DESCRIPTION
**Pull request by ZzEeKkAa**
Update was blocked because `spirv-headers` stopped updating. Now, that https://github.com/conda-forge/spirv-headers-feedstock/pull/15 is merged, the update should be unblocked.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes: #19 
Fixes: #22 

I want to target #23 after https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2586 is merged

## UPD

Block was also due to new [abi version by llvm](https://www.phoronix.com/news/LLVM-N-1-Stable-Versioning) that blocked testing/file picking.

## UPD2

From build log:
```
-- SPIRV-Tools not found; project will be built without --spirv-tools-dis support.
```

So `spirv-tools` must be added to meet this functionality. Thankfully this is only binary dependency, not library one.

### CODE REVIEW

**Comment by ZzEeKkAa** [comment]
@conda-forge-admin, please rerender

**Review by matthiasdiener — APPROVED** [review]

**Comment by ZzEeKkAa** [comment]
@isuruf could you review it, please?

**Comment by ZzEeKkAa** [comment]
@isuruf @matthiasdiener are there anything to be done before merging this PR?

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
